"""phase_4_faculty_assignment_uniqueness

Revision ID: 2028a12246d1
Revises: ea5b672f1b65
Create Date: 2026-09-13 21:29:15.435695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2028a12246d1'
down_revision: Union[str, Sequence[str], None] = 'ea5b672f1b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_subject_assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_faculty_subject_division', ['faculty_id', 'subject_id', 'division_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_subject_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uix_faculty_subject_division', type_='unique')

    # ### end Alembic commands ###
