"""Add CampusSettings

Revision ID: ce0a0332dc91
Revises: 2028a12246d1
Create Date: 2026-09-14 21:40:20.040244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0a0332dc91'
down_revision: Union[str, Sequence[str], None] = '2028a12246d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campus_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campus_settings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campus_settings_id'))

    op.drop_table('campus_settings')
    # ### end Alembic commands ###
