"""phase_1_academic_data

Revision ID: ea5b672f1b65
Revises: 83a38d27e438
Create Date: 2026-09-13 17:02:53.261833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5b672f1b65'
down_revision: Union[str, Sequence[str], None] = '83a38d27e438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_division_name_sem_dept', ['name', 'semester_id', 'department_id'])
        batch_op.create_foreign_key('fk_divisions_department_id', 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_divisions_semester_id', 'semesters', ['semester_id'], ['id'])

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('subject_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key('fk_subjects_semester_id', 'semesters', ['semester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('subject_type')
        batch_op.drop_column('is_active')
        batch_op.drop_column('semester_id')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_column('number')

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_division_name_sem_dept', type_='unique')

    # ### end Alembic commands ###
